language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thek33per/multi-docker-fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thek33per/multi-docker-fib npm test

after_success:
  - docker build -t thek33per/multi-client ./client
  - docker build -t thek33per/multi-nginx ./nginx
  - docker build -t thek33per/multi-server ./server
  - docker build -t thek33per/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thek33per/multi-client
  - docker push thek33per/multi-nginx
  - docker push thek33per/multi-server
  - docker push thek33per/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-956739211007
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
